# Лабораторная работа 3.2 Основы работы с библиотекой NumPy

**Цель работы:**  исследовать базовые возможности библиотеки NumPy языка
программирования Python.

## 1 Вариант

***

* **Индивидуальное**
>Коэффициенты системы линейных уравнений заданы в виде прямоугольной матрицы. С
помощью допустимых преобразований привести систему к треугольному виду. Найти
количество строк, среднее арифметическое элементов которых меньше заданной
величины.

In [3]:
import numpy as np

matrix = np.array([[3.8, 6.7, -1.2, 5.2],
                   [6.4, 1.3, -2.7, 3.8],
                   [2.4, -4.5, 3.5, -0.6]])

for nrow, row in enumerate(matrix):
    # nrow равен номеру строки
    # row содержит саму строку матрицы
    divider = row[nrow] # диагональный элемент
    # Делим на диагональный элемент.
    row /= divider
    # Теперь надо вычесть приведённую строку из всех нижележащих строчек
    for lower_row in matrix[nrow+1:]:
        factor = lower_row[nrow]  # Элемент строки в колонке nrow
        lower_row -= factor*row   # Вычитаем, чтобы получить ноль в колонке nrow

print(matrix)

a = float(input("Введите величину: "))
c = 0
for line in matrix:
    avg = np.mean(line)
    if avg < a:
        c += 1
print("Количество строк, среднее арифметическое которых ниже чем", a, " - ", c)

[[ 1.          1.76315789 -0.31578947  1.36842105]
 [-0.          1.          0.06800211  0.49657354]
 [ 0.          0.          1.          0.09309401]]
Введите величину 3
Количество строк, среднее арифметическое которых ниже чем 3.0 :  3


***

## Ответы на вопросы

1. Каково назначение библиотеки NumPy?

NumPy — это библиотека Python, которую применяют для
математических вычислений: начиная с базовых функций и заканчивая
линейной алгеброй. Полное название библиотеки — Numerical Python
extensions, или «Числовые расширения Python».
Назначение:
Библиотека NumPy предоставляет реализации вычислительных
алгоритмов (в виде функций и операторов), оптимизированные для работы с 
многомерными массивами. В результате любой алгоритм, который может быть
выражен в виде последовательности операций над массивами (матрицами) и
реализованный с использованием NumPy, работает так же быстро, как
эквивалентный код, выполняемый в MATLAB.
Где используется NumPy:
NumPy пользуются ученые для решения
многомерных задач в математике и физике, биоинформатике, вычислительной
химии и даже когнитивной психологии.
Создание новых массивных библиотек. На основе NumPy появляются
новые типы массивов, возможности которых выходят за рамки того, что
предлагает библиотека. Например, библиотеки Dask, CuPy или XND.
Data Science. В основе экосистемы для анализа данных лежит NumPy.
Библиотека используется на всех этапах работы с данными: извлечение и
преобразование, анализ, моделирование и оценка, репрезентация.
Machine Learning. Библиотеки для машинного обучения scikit-learn и
SciPy тоже работают благодаря вычислительным мощностям NumPy.
Визуализация данных. По сравнению непосредственно с Python
возможности NumPy позволяют исследователям визуализировать наборы
данных, которые гораздо больше по размеру. Например, библиотека лежит в
основе системы PyViz, которая включает в себя десятки программ для
визуализации.

2. Что такое массивы ndarray?

Основной элемент библиотеки NumPy — объект ndarray (что значит Nразмерный массив). Этот объект является многомерным однородным массивом
с заранее заданным количеством элементов. Однородный — потому что
практически все объекты в нем одного размера или типа. На самом деле, тип
данных определен другим объектом NumPy, который называется dtype (типданных). Каждый ndarray ассоциирован только с одним типом dtype.
Количество размерностей и объектов массива определяются его
размерностью (shape), кортежем N-положительных целых чисел. Они
указывают размер каждой размерности. Размерности определяются как оси, а количество осей — как ранг.
Еще одна странность массивов NumPy в том, что их размер фиксирован,
а это значит, что после создания объекта его уже нельзя поменять. Это
поведение отличается от такового у списков Python, которые могут
увеличиваться и уменьшаться в размерах.
Простейший способ определить новый объект ndarray — использовать
функцию array(), передав в качестве аргумента Python-список элементов.

3. Как осуществляется доступ к частям многомерного массива?

Доступ к элементам массива осуществляется по целочисленным
индексами, начинается отсчет с 0:
Если представить многомерный массив как систему вложенных
одномерных массивов (линейный массив, элементы которого могут быть
линейными массивами), становится очевидной возможность получать доступ к
подмассивам с использованием неполного набора индексов
При использовании неполного набора индексов, недостающие индексы
неявно заменяются списком всех возможных индексов вдоль соответствующей
оси. Сделать это явным образом можно, поставив ":"
Индексы могут принимать отрицательные целые значения. В этом случае
отсчет ведется от конца массива.

4. Как осуществляется расчет статистик по данным?

Расчет статистик по строкам или столбцам массива
Для начала создадим матрицу, которая нам понадобится в работе.

m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
 print(m)
[[1 2 3 4]
[5 6 7 8]
[9 1 5 7]]
В этом случае будет создан объект типа matrix.
 type(m)
<class 'numpy.matrixlib.defmatrix.matrix'>
Matix можно превратить в ndarray вот так:
 m = np.array(m)
 type(m)
<class 'numpy.ndarray'>
В любом случае наша таблица чисел будет выглядеть следующим
образом.

![jupyter](img/Screenshot_1011.png)

Вызовем функцию вычисления статистики (максимальный элемент) без
аргументов.
 m.max()
9
В этом случает будут обработаны все элементы массива.
![jupyter](img/Screenshot_1012.png)

Если необходимо найти максимальный элемент в каждой строке, то для
этого нужно передать в качестве аргумента параметр axis=1.
 m.max(axis=1)
matrix([[4],
[8],
[9]])

![jupyter](img/Screenshot_1013.png)

Для вычисления статистики по столбцам, передайте в качестве параметра
аргумент axis=0.
 m.max(axis=0)
matrix([[9, 6, 7, 8]])

![jupyter](img/Screenshot_1014.png)


5. Как выполняется выборка данных из массивов ndarray?

Создадим матрицу, с которой будем работать.
 m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
 print(m)
[[1 2 3 4]
[5 6 7 8]
[9 1 5 7]]
Получим вот такую таблицу чисел

![jupyter](img/Screenshot_1015.png)

Извлечем элемент из нашей матрицы с координатами (1, 0), 1 – это номер
строки, 0 – номер столбца.
Здесь и далее, элементы, с которыми мы работаем в матрице будут
окрашены в оранжевый цвет на соответствующей картинке.

![jupyter](img/Screenshot_1016.png)

 m[1, 0]
5
В приведенной записи, в квадратных скобках указывается номер строки
– первой цифрой и номер столбца – второй.
Строка матрицы
Получим вторую строчку матрицы.
![jupyter](img/Screenshot_1017.png)

 m[1, :]
matrix([[5, 6, 7, 8]])
Двоеточие означает “все элементы”, в приведенном примере, первый элемент – это номер строки, второй – указание на то, что необходимо взять
элементы всех столбцов матрицы.

Столбец матрицы

Извлечем третий столбец матрицы 
![jupyter](img/Screenshot_1018.png)

 m[:, 2]
matrix([[3],
[7],
[5]])
Здесь, также как в предыдущем примере, используется двоеточие.
Первый элемент в квадратных скобках означает, что мы возьмем по элементу
из каждой строки, которые находится в столбце, указанном во втором
элементе.

Часть строки матрицы

Иногда возникает задача взять не все элементы строки, а только часть:
рассмотрим пример, когда нам из второй строки нужно извлечь все элементы,
начиная с третьего.
![jupyter](img/Screenshot_1019.png)

m[1, 2:]
matrix([[7, 8]])
Запись “2:” означает, что начиная с третьего столбца включительно (т.к.
нумерация начинается с 0, то третий элемент имеет индекс 2) взять все
оставшиеся в ряду элементы .

Часть столбца матрицы

Аналогично предыдущему примеру, можно извлечь только часть столбца
матрицы.
![jupyter](img/Screenshot_1020.png)

 m[0:2, 1]
matrix([[2],
[6]])
В приведенной записи “0:2” означает: взять все элементы столбца
начиная с индекса 0, заканчивая индексом 2, но последний элемент в результат
не включать.
Непрерывная часть матрицы
Извлечем из заданной матрицы матрицу, располагающуюся так как
показано на рисунке ниже.
![jupyter](img/Screenshot_1021.png)

 m[0:2, 1:3]
matrix([[2, 3],
[6, 7]])
Произвольные столбцы / строки матрицы
Numpy позволяет извлекать произвольный набор столбцов или строк
матрицы, строки (столбцы) которые нужно извлечь передаются в виде списка.

![jupyter](img/Screenshot_1022.png)

 cols = [0, 1, 3]
 m[:, cols]
matrix([[1, 2, 4],
[5, 6, 8],
[9, 1, 7]])